### ISSUE TITLE
Are there other functions to control the play progress? Such as play reversed , seek to?

### ISSUE THREAD

**Issue by jane00** [DenisMondon/easy-animated-vector-drawable#2]
thanks

**Comment by DenisMondon** [comment]
Hi, i'm sorry but no, there are not. Animated vector drawables don't let you control the progress or whatever. It is only a "starting" object.
I recommend you using Lottie images to do what you need: https://airbnb.design/lottie/

See you!
Denis

**Comment by jane00** [comment]
Thanks. I know the lottie library, but it's a third party solution.
